version: '3'
services:
  app:
    container_name: youtube-bot
    build:
      context: .
    command: bash -c "python -m bot.init_models; python -m bot.main"
    ports:
      - "8888:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5436:${DATABASE_PORT}/tcp
    environment:
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_HOST}
      PORT: ${DATABASE_PORT}

volumes:
 postgres_data: